### ISSUE TITLE
UAT Feedback/to-do list

### ISSUE THREAD

**Issue by andrjohns** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#176]
- [ ] After adding a Y axis limit and then deleting your value, it doesn't allow a reset to dynamic resizing, it forces the entry of a value. Work around is to hit the function button, accept the default, then hit the eraser icon - remove conditional formatting
- [ ] After adding an X axis limit it does not hide values/limits when they move behind the y axis
- [ ] Requires multiplier to be 100 to display percentage tooltip correctly for p charts
- [ ] Turning Outlier highlighting on and then off doesn't remove highlighting - Last version works and Funnel works -> Same with Bryan
- [ ] Adding a target value requires the proportion value to be used, adding a y axis limit uses the proportion*100 value for percentage - both are proportion value for funnel
- [ ] SPC Text errors out when a tooltip measure has a value of 'Null'
- [ ] Keep Outliers in Limit Calc conditional formatting button is not working
- [ ] Outlier Highlighting custom formatting is missing fields
- [ ] For non p charts, the rule where points are excluded when the denominator is less than the numerator is removing points. Therefore quite a few points for non p charts have gone missing. 
- [ ] Can't remove additional target value once implemented (Only work around is to click back, hoping that PBI will let you)
- [ ] As a suggestion, the info icon could potentially let users know if there are any missing periods in the data set - i.e for May 2023, there was no data - since sometimes it's a bit hard to spot if there's a missing period in SPC charts. 
- [ ] I still don't understand what maximum ticks does
